apiVersion: v1

kind: Service

metadata:
  name: mlflow-service
  namespace: smartpredict

spec:

  selector:
    app: mlflow

  type: NodePort

  ports:

  - port: 5000
    targetPort: 5000
    nodePort: 30500
